### ISSUE TITLE
[connective-firestore] - delete entity should indicate whether the entity was deleted or not in the delete operation

### ISSUE THREAD

**Issue by codestiff** [codestiff/connective#10]

**Comment by johnmcconnell** [comment]
Closed: https://github.com/codestiff/connective/commit/2fc4d01883205a427c5b4f7cd24ed8257b69e5a1

**Comment by codestiff** [comment]
Closed: https://github.com/codestiff/connective/commit/2fc4d01883205a427c5b4f7cd24ed8257b69e5a1
